name: Feature Request
description: Suggest an idea for this project
title: '[Feature]: '
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Before submitting, please search [existing issues](https://github.com/Zephyruso/zashboard/issues) to see if your idea has already been proposed.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Please provide a clear and concise description of the feature you'd like to request
      placeholder: 'Please describe the feature you want in detail'
    validations:
      required: true
